### ISSUE TITLE
Coding Style

### ISSUE THREAD

**Issue by Dekablade01** [amnmblchllng/survey-list-app#7]
- Classes should not be implemented in the same file
- Explicit Type Force Unwrapping should be avoided. 
- Assigning value into model should be done by the decoder, not by assigning value in the API class
- API Class has too many responsibilities,
    - Fetch token, decode and create Token
    - Use Token make requests for Surveys and decode.
- Access modifier is not set correctly ( private, internal, var, let )
- The omitting self is not consistent.
- Error is more preferable than NSError
- NSError’s user info key `original` is not a standard.
- Using Alamofire's static instance directly should be avoided. 
- Enum, Class, Struct should be named starting with Capital Letter
- errors should conform to Error protocol, not Int
- Creating UIColor with `0xCA/255` is not hard to know what color is it. It is not consistent with UIColor you’re using in `AppDelegate`

**Comment by amnmblchllng** [comment]
> - Classes should not be implemented in the same file

Fixed with PR for #6

> - Explicit Type Force Unwrapping should be avoided. 

Fixed. Some force unwrappings I think are still preferable so I kept them: For example for API's `baseUrl` it would be better to make the build crash @ start-time than to have e.g. `""` and crash later; also for Interface Builder elements where it is forced by default, and registered collection view cells to spot forgotten registrations early (thus if we cannot continue without).

>- Assigning value into model should be done by the decoder, not by assigning value in the API class

Fixed

>- API Class has too many responsibilities,
>    - Fetch token, decode and create Token
>    - Use Token make requests for Surveys and decode.

Fixed

>- Access modifier is not set correctly ( private, internal, var, let )

Fixed

>- The omitting self is not consistent.

Fixed. Now omitted outside of closures and when not conflicting with locals

>- Error is more preferable than NSError

Fixed. Using Swift Error now

>- NSError’s user info key `original` is not a standard.

Fixed. Nest in Swift Error enum

>- Using Alamofire's static instance directly should be avoided. 

Fixed

>- Enum, Class, Struct should be named starting with Capital Letter

Fixed

>- errors should conform to Error protocol, not Int

Fixed

>- Creating UIColor with `0xCA/255` is not hard to know what color is it. It is not consistent with 
>UIColor you’re using in `AppDelegate`

Fixed. Add UIColor hexRgba extension
